config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'cocktails#index'
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :instructions, only: [:new, :create] do 
      resources :ingredients, only: [:new, :create]
    end
  end

  resources :ingredients, only: [:new, :create]

  resources :instructions, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  belongs_to :user

  has_many :instructions
  has_many :ingredients, through: :instructions
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :quantity, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient,
  message: "should had 1 time each ingredient only" }
  validates :ingredient, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :instructions
  before_save :capitalize_name

  validates :name, presence: true
  validates_uniqueness_of :name, :case_sensitive => false

  def capitalize_name
    self.name.capitalize!
  end

end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :quantitynb, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient,
  message: "should had 1 time each ingredient only" }
  validates :ingredient, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cocktails
  has_many :instructions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?


  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr? 
  end

  def store_user_location!
    # :user is the scope we are authenticating
    store_location_for(:user, request.fullpath)
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  def after_sign_out_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end


end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @cocktails= policy_scope(Cocktail)
  end

  def show
    @cocktail= Cocktail.find(params[:id])
    authorize @cocktail
    @instruction = Instruction.new
    authorize @instruction
    @ingredient = Ingredient.new
  end

  def new
    @cocktail = Cocktail.new
    authorize @cocktail
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.user = current_user
    authorize @cocktail
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private
  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new]

  def new
    @ingredient = Ingredient.new
    authorize @ingredient
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    authorize @ingredient
    if @ingredient.save
      redirect_to request.referrer
    else
      flash.now[:alert] = 'There was a problem adding this ingredient'
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @instruction = Instruction.new
    authorize @instruction
  end

  def create
    @instruction = Instruction.new(instruction_params)
    authorize @instruction
    @cocktail = Cocktail.find(params[:cocktail_id])
    @instruction.cocktail = @cocktail
    if @instruction.save
      redirect_to request.referrer
    else 
      redirect_to request.referrer
    end
  end

  def edit
    @instruction = Instruction.find(params[:id])
  end

  def update
    @instruction = Instruction.find(params[:id])
    @instruction.update(instruction_params)

    redirect_to cocktails_path(@cocktail)
  end

  def destroy
    @instruction = Instruction.find(params[:id])
    authorize @instruction
    @cocktail = @instruction.cocktail
    @instruction.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def instruction_params
    params.require(:instruction).permit(:quantity, :quantitynb, :ingredient_id, :cocktail_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cocktails/index.html.erb
<div id="log">
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fas fa-user"></i><p>Log out</p>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
    <i class="fas fa-user"></i>
    <p>Log in</p>
    <% end %>
  <% end %>
</div>
  
  <div class="all-index-page">
  <div class="header" style="background-image:url('<%= cl_image_path('cocktail-cascade_uibo7g') %>')">
    <p class='header-title'>LOOK AT</p>
    <h1 class='header-title'><span class='title-home'>THE <span class='header-shadow'>COCKTAILS</span></span></h1>
    <p class='header-title'>YOU'RE GONNA TASTE</p>
  </div>

  <div class='cards-box'> 
    <% @allcocktails = @cocktails.sort_by {|obj| obj.name} %>
    <% @allcocktails.each_with_index do |cocktail, index| %>
      <% if index % 2 == 0 %>
        <div class='card-low'>
          <%= link_to (image_tag cocktail.photo),  cocktail_path(cocktail) %>
          <%= link_to cocktail.name, cocktail_path(cocktail), class: 'cocktail-name' %>
        </div>
      <% else %>
        <div class='card-normal'>
          <%= link_to (image_tag cocktail.photo),  cocktail_path(cocktail) %>
          <%= link_to cocktail.name, cocktail_path(cocktail), class: 'cocktail-name' %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id='missing-cocktail' style="background-image:url('<%= cl_image_path('test_bytnos') %>')">
    <h2 style="color:white">Can't find your favorite cocktail? <br>Add it!</h2>
    <%= link_to 'Add a cocktail', new_cocktail_path, class:"btn-white", id:'btn-add-cocktail' %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div id="log">
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fas fa-user"></i><p>Log out</p>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
    <i class="fas fa-user"></i>
    <p>Log in</p>
    <% end %>
  <% end %>
</div>

<div class='new-cocktail'>
  <div class="new-img-desktop" style="background-image:url('<%= cl_image_path('half-cascade-cocktails_ebfafn') %>')">
     <%= link_to cocktails_path, class:'back-to-cocktails' do %>
    <i class="fas fa-long-arrow-alt-left"></i><p class='back-to-cocktails'>Back to all cocktails</p>
   <% end %>
  </div>
  <div class="new-img-mobile" style="background-image:url('<%= cl_image_path('mobile_cascade_cocktails_lo8pee') %>')">
     <%= link_to cocktails_path, class:'back-to-cocktails' do %>
    <i class="fas fa-long-arrow-alt-left"></i><p class='back-to-cocktails'>Back to all cocktails</p>
   <% end %> 
  </div>

  <div class='new-cocktail-form-mobile'>
    <h1 class='new-cocktail-title'>Your <span>new cocktail</span></h1>
    <%= simple_form_for(@cocktail) do |f| %>
      <%= f.text_field :name, placeholder:'Cocktail\'s name...', id:'form-name'%>
      <%= f.input :photo, as: :file, label:false %>
      <%= f.submit class:'btn-new-submit' %>
    <% end %>
  </div>

  <div class='new-cocktail-form-desktop'>
    <h1 class='new-cocktail-title'>What is your <span>new cocktail</span> ?</h1>
    <%= simple_form_for(@cocktail) do |f| %>
      <%= f.text_field :name, placeholder:'Cocktail\'s name', id:'form-name'  %>
      <%= f.input :photo, as: :file, label:false %>
      <%= f.submit class:'btn-new-submit'%>
  </div>
      
    <% end %>


</div>

app/views/cocktails/show.html.erb
<div id="log">
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fas fa-user"></i><p>Log out</p>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path do %>
    <i class="fas fa-user"></i>
    <p>Log in</p>
    <% end %>
  <% end %>
</div>

<div class="cocktail-show-header">
  <div style="background-image: url(<%= rails_blob_url(@cocktail.photo) %>)", class="photo-cocktail-show">
   <%= link_to cocktails_path, class:'back-to-cocktails' do %>
    <i class="fas fa-long-arrow-alt-left"></i><p class='back-to-cocktails'>Back to all cocktails</p>
   <% end %>
  </div>

  <div class="cocktail-show-info">
    <h1 class="cocktail-name-title"><%= @cocktail.name %></h1>

    <% if @cocktail.instructions == [] %>
      <h2 style="margin-bottom: 40px">This cocktail has no recipe at the moment.</h2>
      <% if user_signed_in? %>
        <% if @cocktail.user == current_user %>
          <a class='circle' id='btn-total-form'><i class="fas fa-plus buble-i"></i> Feed this cocktail</a>
          <a class='circle d-none' id='btn-hide-total-form'><i class="fas fa-minus buble-i"></i> Feed this cocktail </a>
          <%= render "instructions/new", cocktail: @cocktail, instruction: @instruction %>
        <% end %>
      <% else %>
      <div class='have-to-log'>
          <i class="fas fa-cocktail buble-i"></i>
        <p>This cocktail is yours? <%= link_to 'Log in', new_user_session_path %> to modify it.</p>
      </div>
      <% end %>

    <% else %>
      <div class="quantity-counter">
        <i class="fas fa-minus quantity-minus"></i>
        <input id="recipe-counter" type="integer" value="1" min="1" max="" >
        <p id="one-glass" class="">glass</p>
        <p id="several-glasses" class="d-none">glasses</p>
        <i class="fas fa-plus quantity-plus"></i>
      </div>
      <div class='instructions-list'>
        <% @cocktail.instructions.each do |instruction| %>
          <div class='instructions-all'>
            <p><span class='to-change'><%= instruction.quantitynb %></span><span class="to-feed"></span> <%= instruction.quantity.downcase %> of  <%= instruction.ingredient.name.downcase %></p>
            <% if @cocktail.user == current_user %>
              <%= link_to instruction_path(instruction), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
            <% end %>
          </div>
          <% end %>
        </div>
      <% if user_signed_in? %>
        <% if @cocktail.user == current_user %>
          <a class='circle' id='btn-total-form'><i class="fas fa-plus buble-i"></i> Add an instruction</a>
          <a class='circle d-none' id='btn-hide-total-form'><i class="fas fa-minus buble-i"></i> Add an instruction</a>
          <%= render "instructions/new", cocktail: @cocktail, instruction: @instruction %>
        <% else %>
          <p style='margin-top: 80px'>This cocktail is not yours, so you can't modify it 😉</p>
        <% end %>
      <% else%>
        <div class='have-to-log'>
          <i class="fas fa-cocktail buble-i"></i>
          <p>This cocktail is yours? <%= link_to 'Log in', new_user_session_path %> to modify it.</p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<% if user_signed_in? && @cocktail.user == current_user %>
  <div id="new-ingredient">
    <h2 class="white-title">You need a <u>new ingredient</u> to feed your cocktail? <u>Add it!</u></h2>
    <%= render "ingredients/new", ingredient: @ingredient %>
  </div>
<% end %>

app/views/doses/_new.html.erb
<div class="d-none" id="form-add-dose">
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :quantity %>
  <%= f.submit %>
<% end %>
</div>

app/views/ingredients/_new.html.erb
<%= simple_form_for(ingredient, remote: true) do |f| %>
  <div id='ingredient-form'>
    <div>
      <%= f.input :name, label: false, placeholder:'New ingredient' %>
    </div>
    <div>
      <button name="button" type="submit" id="send-ingredient">
        <i class="fas fa-arrow-right" aria-hidden="true"></i>
      </button>
    </div>
  </div>
<% end %>

app/views/instructions/_new.html.erb
<div id="instruction-form" class='d-none'>
<p><b>For <u>one</u> glass</b></p>
<%= simple_form_for([cocktail, instruction], remote: true) do |f| %>
  <%= f.association :ingredient, collection: Ingredient.order('name ASC'), :prompt => "Choose an ingredient" %>
  <div class="quantity">
    <%= f.input :quantitynb, as: :numeric, placeholder:'Ex: 1', label: 'Quantity' %>
    <%= f.input :quantity, placeholder:'Ex: cl', label: 'Unit' %>
  </div>
  <%= f.submit "ADD THE NEW DOSE", class:'submit-instruction' %>

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CocktailCode</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>      
    <%= yield %>
  </body>
</html>